version: 2.1
jobs:
  test-fuzzy-search:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install rapidfuzz
      - run:
          name: Run fuzzy search tests
          command: pytest src/database/tests/test_fuzzy_search.py
workflows:
  version: 2
  fuzzy_search:
    jobs:
      - test-fuzzy-search